<?php

require_once( "itinerary.php" );
require_once( "map.php" );
require_once( "grid.php" );

function vfringe_extras_block_info() {
  // The machine name of the block
  $blocks[''] = array(
    'info'  => t('VFringe Itinerary'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

function vfringe_extras_menu() {
  $items = array();
  
  // Create the actual OpenData URL (there is no .ttl file, it is a URL that served as plain text
  $items['vfringe-grid'] = array(
    'page callback' => 'vfringe_extras_serve_grid',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['vfringe-map'] = array(
    'page callback' => 'vfringe_extras_serve_map',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['vfringe-itinerary'] = array(
    'page callback' => 'vfringe_extras_serve_itinerary',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
} 

function vfringe_extras_block_view($delta) {
  $block = array();

  if( $delta == "itinerary" ) {
    return vfringe_extras_block_view_itinerary();
  }

  return $block;
}

function vfringe_extras_taxonomy_term_single_value($term,$field,$default=null) {
  $items = field_get_items( "taxonomy_term", $term, $field );
  $value = trim($items[0]['value']);
  if( $value ) { return $value; }
  return $default;
}

// used to make debugging queries easier
function vfringe_extras_query_alter($query) {
  if ($query->hasTag('efq_debug')) {
//    dpm((string)$query);
  }
}



function vfringe_extras_load_pois() {
  
  $pois = &drupal_static(__FUNCTION__);
  if( !$pois ) {
    $query = new EntityFieldQuery();
    $entities = $query->entityCondition('entity_type', 'taxonomy_term')
                   ->addTag('efq_debug')
                   ->entityCondition('bundle','points_of_interest' )
                   ->execute();
    $pois = entity_load('taxonomy_term',array_keys($entities['taxonomy_term']));
  }
  return $pois;
}

function vfringe_extras_load_venues() {
  
  $venues = &drupal_static(__FUNCTION__);
  if( !$venues ) {
    $query = new EntityFieldQuery();
    $entities = $query->entityCondition('entity_type', 'taxonomy_term')
                   ->addTag('efq_debug')
                   ->entityCondition('bundle','event_venues' )
                   ->execute();
    $venues = entity_load('taxonomy_term',array_keys($entities['taxonomy_term']));
  }
  return $venues;
}

